#!/bin/bash

# Update all system
sudo pacman -Syyuu

# Install paru
sudo pacman -S rustup pkg-config
rustup update stable
rustup default stable
git clone https://aur.archlinux.org/paru.git /tmp/paru
(cd /tmp/paru && makepkg -si)

# Install packages
sudo paru -S --needed - < ./pkglist.txt

# Configure vscode 
cat ./vscode/extensions.txt | grep ^[^#] | xargs -I {} code --install-extension {} --force
cp ./vscode/settings.json "~/.config/Code - OSS/User/settings.json"


# Install .config folder
mkdir -p ~/.config
cp -r ./.config ~/.config
